/**
 * NEXUS AI - Code API Routes
 * Handles all code-related endpoints
 */

const express = require('express');
const router = express.Router();
const { v4: uuidv4 } = require('uuid');

// Code execution sandbox
const codeSessions = new Map();

// Generate code
router.post('/generate', async (req, res) => {
  try {
    const { prompt, language, context,framework } = req.body;
    
    // AI code generation logic
    const codeTemplates = {
      javascript: generateJavaScript(prompt, framework),
      python: generatePython(prompt, framework),
      react: generateReact(prompt, context),
      node: generateNodeAPI(prompt, context)
    };

    res.json({
      success: true,
      code: codeTemplates[language] || codeTemplates.javascript,
      language: language || 'javascript',
      tokens: Math.floor(prompt.length / 4),
      lines: (codeTemplates[language] || codeTemplates.javascript).split('\n').length
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Execute code
router.post('/execute', async (req, res) => {
  try {
    const { code, language, input } = req.body;
    const sessionId = uuidv4();
    
    // Simulated execution (use sandpack in production)
    const result = {
      output: `Executed successfully\nOutput: ${code.substring(0, 50)}...`,
      status: 'success',
      executionTime: Math.floor(Math.random() * 100) + 10,
      memory: Math.floor(Math.random() * 50) + 10
    };

    codeSessions.set(sessionId, {
      id: sessionId,
      code,
      result,
      timestamp: Date.now()
    });

    res.json({
      success: true,
      sessionId,
      output: result.output,
      status: result.status,
      executionTime: result.executionTime
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Code review
router.post('/review', async (req, res) => {
  try {
    const { code, language } = req.body;

    const issues = [];
    const lines = code.split('\n');

    lines.forEach((line, idx) => {
      // Common issues detection
      if (line.includes('console.log') && !line.includes('//')) {
        issues.push({ line: idx + 1, severity: 'warning', message: 'Remove console.log in production' });
      }
      if (line.includes('TODO')) {
        issues.push({ line: idx + 1, severity: 'info', message: 'TODO comment found' });
      }
      if (line.length > 120) {
        issues.push({ line: idx + 1, severity: 'warning', message: 'Line too long (>120 chars)' });
      }
    });

    const score = Math.max(0, 100 - issues.length * 10);

    res.json({
      success: true,
      issues,
      score,
      suggestions: issues.length > 0 ? 'Consider fixing the issues above' : 'Code looks good!',
      complexity: code.length > 500 ? 'High' : 'Low'
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Format code
router.post('/format', async (req, res) => {
  try {
    const { code, language } = req.body;
    
    // Simple formatting (use prettier in production)
    const formatted = code
      .replace(/\s+/g, ' ')
      .replace(/;/g, ';\n')
      .replace(/{/g, '{\n')
      .replace(/}/g, '\n}');

    res.json({
      success: true,
      formatted
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get supported languages
router.get('/languages', (req, res) => {
  res.json({
    success: true,
    languages: Object.keys(supportedLanguages)
  });
});

// Code templates generators
function generateJavaScript(prompt, framework) {
  return `// Generated by NEXUS AI
// ${prompt}

${framework === 'express' ? `const express = require('express');
const app = express();

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Hello World' });
});` : `function processData(input) {
  // Implementation
  return input.map(item => item);
}`}
`;
}

function generatePython(prompt, framework) {
  return `# Generated by NEXUS AI
# ${prompt}

def process_data(data):
    """Process input data"""
    return [item for item in data]
`;
}

function generateReact(prompt, context) {
  return `// Generated by NEXUS AI - React Component
import React, { useState } from 'react';

export default function ${prompt.replace(/[^a-zA-Z]/g, '')}() {
  const [state, setState] = useState(null);
  
  return (
    <div className="component">
      <h1>${prompt}</h1>
    </div>
  );
}
`;
}

function generateNodeAPI(prompt, context) {
  return `// NEXUS AI Generated - REST API
const express = require('express');
const router = express.Router();

${prompt}

router.get('/', (req, res) => {
  res.json({ data: [] });
});

module.exports = router;
`;
}

module.exports = router;
